const data = {
  list: [
    {
      appid: 1,
      slotid: 1,
      operation: 1,
      format: '1',
      name: 'helloworld',
      template: '0',
      template_h5: 'null',
      fb_id: null,
      admob_id: null,
      virtual_currency_name: null,
      server_callback_url: null,
      server_callback_key: null,
      rewarded_amount: 'null',
      video_screen_type: '1',
      priority: ['ct', 'fb', 'ad_c', 'ad_d']
    },
    {
      appid: 1,
      slotid: 2,
      operation: 1,
      format: '2',
      name: 'helloworld',
      template: '1',
      template_h5: null,
      fb_id: null,
      admob_id: null,
      virtual_currency_name: null,
      server_callback_url: null,
      server_callback_key: null,
      rewarded_amount: 'null',
      video_screen_type: '1',
      priority: ['ct', 'fb', 'ad_c', 'ad_d']
    },
    {
      appid: 1,
      slotid: 3,
      operation: 1,
      format: '3',
      name: 'helloworld',
      template: '1',
      template_h5: null,
      fb_id: null,
      admob_id: null,
      virtual_currency_name: null,
      server_callback_url: null,
      server_callback_key: null,
      rewarded_amount: 'null',
      video_screen_type: '1',
      priority: ['ct', 'fb', 'ad_c', 'ad_d']
    },
    {
      appid: 1,
      slotid: 4,
      operation: 1,
      format: '4',
      name: 'helloworld',
      template: '1',
      template_h5: null,
      fb_id: null,
      admob_id: null,
      virtual_currency_name: null,
      server_callback_url: null,
      server_callback_key: null,
      rewarded_amount: 'null',
      video_screen_type: '1',
      priority: ['ct', 'fb', 'ad_c', 'ad_d']
    },
    {
      appid: 1,
      slotid: 7,
      operation: 1,
      format: '7',
      name: 'helloworld',
      template: '1',
      template_h5: null,
      fb_id: null,
      admob_id: null,
      virtual_currency_name: null,
      server_callback_url: null,
      server_callback_key: null,
      rewarded_amount: 'null',
      video_screen_type: '1',
      priority: ['ct', 'fb', 'ad_c', 'ad_d']
    },
    {
      appid: 2,
      slotid: 1,
      operation: 1,
      format: '7',
      name: 'helloworld2',
      template: '1',
      template_h5: null,
      fb_id: null,
      admob_id: null,
      virtual_currency_name: null,
      server_callback_url: null,
      server_callback_key: null,
      rewarded_amount: 'null',
      video_screen_type: '2',
      priority: ['fb', 'ct', 'ad_c', 'ad_d']
    }
  ]
}
export default {
  state: data
}
